### ISSUE TITLE
You are missing "r" as the last character in the pod dependency, where you specified: pod 'KSYAirStreamer'

### ISSUE THREAD

**Issue by yoninezer** [ksvc/KSYAirStreamer_iOS#1]

**Comment by fpzeng** [comment]
Do you mean this [podfile file](https://github.com/ksvc/KSYAirStreamer_iOS/blob/master/demo/Podfile) ?

**Comment by pengbins** [comment]
fixed in https://github.com/ksvc/KSYAirStreamer_iOS/commit/ff648bf375b6231bb2d889831da8b6b6d1e01e60

thank you~
